sudo: false
language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.7
addons:
  apt:
    packages:
      - libc6-i386
      - lib32z1
      - lib32stdc++6
before_install:
  - export PATH=${PATH}:./vendor/bundle
  - wget http://dl.google.com/android/android-sdk_r24-linux.tgz
  - tar xf android-sdk_r24-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export ANDROID_SDK_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo yes | android update sdk --all --filter platform-tools --no-ui
  - echo yes | android update sdk --all --filter build-tools-25.0.0 --no-ui
  - echo yes | android update sdk --all --filter android-25 --no-ui
  - echo yes | android update sdk --all --filter extra-android-support --no-ui
  - echo yes | android update sdk --all --filter extra-android-m2repository --no-ui
  - echo yes | android update sdk --all --filter extra-google-m2repository --no-ui
  - mv debug.properties.default debug.properties
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test
